// @generated by tools/generate_contracts.py; do not edit.

pub mod protocol {
    pub const BLE_BEACON_JITTER_SECONDS: u64 = 120;
    pub const BLE_BEACON_ROTATION_SECONDS: u64 = 600;
    pub const BLE_CONTROL_RX_UUID: &str = "6f1d0002-8f6b-4d5b-9c61-57c43d4d4d31";
    pub const BLE_CONTROL_TX_UUID: &str = "6f1d0003-8f6b-4d5b-9c61-57c43d4d4d31";
    pub const BLE_DATA_RX_UUID: &str = "6f1d0004-8f6b-4d5b-9c61-57c43d4d4d31";
    pub const BLE_DATA_TX_UUID: &str = "6f1d0005-8f6b-4d5b-9c61-57c43d4d4d31";
    pub const BLE_GATT_CONNECT_TIMEOUT_SECONDS: u64 = 12;
    pub const BLE_MAX_BUNDLE_REQUESTS_PER_FRAME: u64 = 16;
    pub const BLE_MAX_CHUNK_COUNT: u64 = 1024;
    pub const BLE_MAX_INVENTORY_ENTRIES_PER_PAGE: u64 = 32;
    pub const BLE_NOISE_HANDSHAKE_TIMEOUT_SECONDS: u64 = 10;
    pub const BLE_PARTIAL_TRANSFER_RETENTION_SECONDS: u64 = 600;
    pub const BLE_SERVICE_DISCOVERY_TIMEOUT_SECONDS: u64 = 8;
    pub const BLE_SERVICE_UUID: &str = "6f1d0001-8f6b-4d5b-9c61-57c43d4d4d31";
    pub const BLE_WIRE_CONTROL_RESERVE_BYTES: u64 = 4096;
    pub const BLE_WIRE_MAX_CREDIT_BYTES: u64 = 262144;
    pub const BLE_WIRE_MAX_LOGICAL_FRAME_BYTES: u64 = 65536;
    pub const BLE_WIRE_MAX_SEGMENT_COUNT: u64 = 1024;
    pub const BLE_WIRE_OUTER_HEADER_BYTES: u64 = 16;
    pub const BLE_WIRE_OUTER_MAGIC: u64 = 216;
    pub const BLE_WIRE_OUTER_VERSION: u64 = 1;
    pub const CAPABILITIES_CONTROL_RECEIPT: u64 = 16;
    pub const CAPABILITIES_CREDIT_FLOW: u64 = 8;
    pub const CAPABILITIES_INVENTORY_PAGING: u64 = 2;
    pub const CAPABILITIES_KNOWN_MASK: u64 = 31;
    pub const CAPABILITIES_NOISE_XX: u64 = 1;
    pub const CAPABILITIES_RESUME_BITMAP: u64 = 4;
    pub const LOCAL_ENCRYPTION_ENVELOPE_VERSION: u64 = 1;
    pub const LOCAL_ENCRYPTION_NONCE_BYTES: u64 = 24;
    pub const LOCAL_ENCRYPTION_TAG_BYTES: u64 = 16;
    pub const PROTOCOL_BLE_CLA_VERSION: u64 = 1;
    pub const PROTOCOL_DME_VERSION: u64 = 1;
    pub const PROTOCOL_MAJOR: u64 = 1;
    pub const PROTOCOL_MAX_BUNDLE_BYTES: u64 = 12288;
    pub const PROTOCOL_MAX_DME_PAYLOAD_BYTES: u64 = 8192;
    pub const PROTOCOL_MAX_HPKE_CIPHERTEXT_BYTES: u64 = 8118;
    pub const PROTOCOL_MAX_TEXT_CHARS: u64 = 2000;
    pub const PROTOCOL_MAX_TEXT_UTF8_BYTES: u64 = 7800;
    pub const PROTOCOL_MINOR: u64 = 0;
    pub const PROTOCOL_ROUTING_BLOCK_TYPE: u64 = 192;
    pub const REPLAY_WINDOW_BITS: u64 = 4096;
    pub const REPLAY_WINDOW_BYTES: u64 = 512;
    pub const ROUTING_CANCEL_COPY_TOKENS: u64 = 12;
    pub const ROUTING_CANCEL_HOP_LIMIT: u64 = 16;
    pub const ROUTING_CANCEL_PRIORITY: u64 = 0;
    pub const ROUTING_CANCEL_TTL_SECONDS: u64 = 604800;
    pub const ROUTING_CHECK_IN_COPY_TOKENS: u64 = 8;
    pub const ROUTING_CHECK_IN_HOP_LIMIT: u64 = 12;
    pub const ROUTING_CHECK_IN_PRIORITY: u64 = 1;
    pub const ROUTING_CHECK_IN_TTL_SECONDS: u64 = 172800;
    pub const ROUTING_DIRECT_TEXT_COPY_TOKENS: u64 = 6;
    pub const ROUTING_DIRECT_TEXT_HOP_LIMIT: u64 = 12;
    pub const ROUTING_DIRECT_TEXT_PRIORITY: u64 = 2;
    pub const ROUTING_DIRECT_TEXT_TTL_SECONDS: u64 = 259200;
    pub const ROUTING_LOCATION_UPDATE_COPY_TOKENS: u64 = 8;
    pub const ROUTING_LOCATION_UPDATE_HOP_LIMIT: u64 = 12;
    pub const ROUTING_LOCATION_UPDATE_PRIORITY: u64 = 1;
    pub const ROUTING_LOCATION_UPDATE_TTL_SECONDS: u64 = 86400;
    pub const ROUTING_PRIVATE_SOS_COPY_TOKENS: u64 = 12;
    pub const ROUTING_PRIVATE_SOS_HOP_LIMIT: u64 = 16;
    pub const ROUTING_PRIVATE_SOS_PRIORITY: u64 = 0;
    pub const ROUTING_PRIVATE_SOS_TTL_SECONDS: u64 = 86400;
    pub const ROUTING_RECEIPT_COPY_TOKENS: u64 = 12;
    pub const ROUTING_RECEIPT_HOP_LIMIT: u64 = 16;
    pub const ROUTING_RECEIPT_PRIORITY: u64 = 0;
    pub const ROUTING_RECEIPT_TTL_SECONDS: u64 = 604800;
    pub const STORAGE_DEFAULT_RELAY_QUOTA_BYTES: u64 = 33554432;
    pub const STORAGE_PARTIAL_TOTAL_BYTES: u64 = 4194304;
    pub const STORAGE_PER_INGRESS_PEER_DAILY_BYTES: u64 = 8388608;
    pub const STORAGE_PER_INGRESS_PEER_UNVERIFIED_DIRECT_DAILY_BYTES: u64 = 2097152;
    pub const STORAGE_PER_SOURCE_BYTES: u64 = 4194304;
    pub const STORAGE_PRIORITY_RESERVED_BYTES: u64 = 8388608;
}

pub mod state_codes {
    pub const BUNDLE_STATE_COMMITTED: i64 = 0;
    pub const BUNDLE_STATE_EVICTION_PENDING: i64 = 6;
    pub const BUNDLE_STATE_EXPIRED: i64 = 4;
    pub const BUNDLE_STATE_OFFER_SUPPRESSED: i64 = 1;
    pub const BUNDLE_STATE_QUARANTINED: i64 = 5;
    pub const BUNDLE_STATE_TERMINAL_CANCEL: i64 = 3;
    pub const BUNDLE_STATE_TERMINAL_RECEIPT: i64 = 2;
    pub const DIAGNOSTIC_SEVERITY_CRITICAL: i64 = 3;
    pub const DIAGNOSTIC_SEVERITY_ERROR: i64 = 2;
    pub const DIAGNOSTIC_SEVERITY_INFO: i64 = 0;
    pub const DIAGNOSTIC_SEVERITY_WARNING: i64 = 1;
    pub const DIRECTION_INBOUND: i64 = 1;
    pub const DIRECTION_OUTBOUND: i64 = 0;
    pub const MESSAGE_DELIVERY_FAILED_LOCAL: i64 = 9;
    pub const MESSAGE_DELIVERY_INBOUND_CANCELED: i64 = 8;
    pub const MESSAGE_DELIVERY_INBOUND_RECEIVED: i64 = 7;
    pub const MESSAGE_DELIVERY_OUTBOUND_CANCEL_PROPAGATING: i64 = 3;
    pub const MESSAGE_DELIVERY_OUTBOUND_CANCELED_CONFIRMED: i64 = 4;
    pub const MESSAGE_DELIVERY_OUTBOUND_CANCELED_UNCONFIRMED: i64 = 5;
    pub const MESSAGE_DELIVERY_OUTBOUND_EXPIRED: i64 = 6;
    pub const MESSAGE_DELIVERY_OUTBOUND_RECEIPT_CONFIRMED: i64 = 2;
    pub const MESSAGE_DELIVERY_OUTBOUND_RELAYED: i64 = 1;
    pub const MESSAGE_DELIVERY_OUTBOUND_STORED: i64 = 0;
    pub const MESSAGE_DELIVERY_QUARANTINED: i64 = 10;
    pub const PENDING_CONTROL_STATE_APPLIED: i64 = 1;
    pub const PENDING_CONTROL_STATE_CONFLICT_QUARANTINED: i64 = 2;
    pub const PENDING_CONTROL_STATE_EXPIRED: i64 = 3;
    pub const PENDING_CONTROL_STATE_WAITING_FOR_ORIGINAL: i64 = 0;
    pub const TOKEN_GRANT_STATE_RELEASED: i64 = 3;
    pub const TOKEN_GRANT_STATE_RESERVED: i64 = 0;
    pub const TOKEN_GRANT_STATE_TRANSFERRED: i64 = 2;
    pub const TOKEN_GRANT_STATE_UNCERTAIN: i64 = 1;
    pub const TRANSFER_STATE_ABORTED: i64 = 9;
    pub const TRANSFER_STATE_COMMITTED: i64 = 3;
    pub const TRANSFER_STATE_FAILED_RETRYABLE: i64 = 8;
    pub const TRANSFER_STATE_READY_TO_COMMIT: i64 = 2;
    pub const TRANSFER_STATE_RECEIVING_CHUNKS: i64 = 1;
    pub const TRANSFER_STATE_RECEIVING_META: i64 = 0;
    pub const TRANSFER_STATE_REJECTED: i64 = 7;
    pub const TRANSFER_STATE_SENDING: i64 = 4;
    pub const TRANSFER_STATE_UNCERTAIN_COMMIT: i64 = 6;
    pub const TRANSFER_STATE_WAITING_ACK: i64 = 5;
    pub const VERSION: i64 = 1;

    pub const ALL: &[(&str, i64)] = &[
        ("bundle_state_committed", 0),
        ("bundle_state_eviction_pending", 6),
        ("bundle_state_expired", 4),
        ("bundle_state_offer_suppressed", 1),
        ("bundle_state_quarantined", 5),
        ("bundle_state_terminal_cancel", 3),
        ("bundle_state_terminal_receipt", 2),
        ("diagnostic_severity_critical", 3),
        ("diagnostic_severity_error", 2),
        ("diagnostic_severity_info", 0),
        ("diagnostic_severity_warning", 1),
        ("direction_inbound", 1),
        ("direction_outbound", 0),
        ("message_delivery_failed_local", 9),
        ("message_delivery_inbound_canceled", 8),
        ("message_delivery_inbound_received", 7),
        ("message_delivery_outbound_cancel_propagating", 3),
        ("message_delivery_outbound_canceled_confirmed", 4),
        ("message_delivery_outbound_canceled_unconfirmed", 5),
        ("message_delivery_outbound_expired", 6),
        ("message_delivery_outbound_receipt_confirmed", 2),
        ("message_delivery_outbound_relayed", 1),
        ("message_delivery_outbound_stored", 0),
        ("message_delivery_quarantined", 10),
        ("pending_control_state_applied", 1),
        ("pending_control_state_conflict_quarantined", 2),
        ("pending_control_state_expired", 3),
        ("pending_control_state_waiting_for_original", 0),
        ("token_grant_state_released", 3),
        ("token_grant_state_reserved", 0),
        ("token_grant_state_transferred", 2),
        ("token_grant_state_uncertain", 1),
        ("transfer_state_aborted", 9),
        ("transfer_state_committed", 3),
        ("transfer_state_failed_retryable", 8),
        ("transfer_state_ready_to_commit", 2),
        ("transfer_state_receiving_chunks", 1),
        ("transfer_state_receiving_meta", 0),
        ("transfer_state_rejected", 7),
        ("transfer_state_sending", 4),
        ("transfer_state_uncertain_commit", 6),
        ("transfer_state_waiting_ack", 5),
    ];
}
