#!/usr/bin/env python3
"""Generate Rust and Kotlin constants from the normative TOML contracts."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PROTOCOL = ROOT / "contracts" / "protocol_constants.toml"
STATES = ROOT / "contracts" / "state_codes.toml"
RUST_OUTPUT = ROOT / "core" / "mesh-types" / "src" / "generated_contracts.rs"
KOTLIN_OUTPUT = (
    ROOT
    / "apps"
    / "android"
    / "domain"
    / "src"
    / "main"
    / "kotlin"
    / "org"
    / "disastermesh"
    / "android"
    / "domain"
    / "GeneratedContracts.kt"
)


def flatten(value: dict[str, Any], prefix: tuple[str, ...] = ()) -> list[tuple[str, Any]]:
    result: list[tuple[str, Any]] = []
    for key in sorted(value):
        item = value[key]
        path = (*prefix, key)
        if isinstance(item, dict):
            result.extend(flatten(item, path))
        else:
            result.append(("_".join(path), item))
    return result


def identifier(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper()


def rust_literal(value: Any) -> tuple[str, str]:
    if isinstance(value, bool):
        return ("bool", str(value).lower())
    if isinstance(value, int):
        return ("u64", str(value))
    if isinstance(value, str):
        return ("&str", json.dumps(value))
    raise TypeError(f"unsupported TOML value: {value!r}")


def kotlin_literal(value: Any) -> tuple[str, str]:
    if isinstance(value, bool):
        return ("Boolean", str(value).lower())
    if isinstance(value, int):
        return ("Long", f"{value}L")
    if isinstance(value, str):
        return ("String", json.dumps(value))
    raise TypeError(f"unsupported TOML value: {value!r}")


def render_rust(protocol: dict[str, Any], states: dict[str, Any]) -> str:
    lines = [
        "// @generated by tools/generate_contracts.py; do not edit.",
        "",
        "pub mod protocol {",
    ]
    for name, value in flatten(protocol):
        value_type, literal = rust_literal(value)
        lines.append(f"    pub const {identifier(name)}: {value_type} = {literal};")
    lines.extend(["}", "", "pub mod state_codes {"])
    state_entries: list[tuple[str, int]] = []
    for name, value in flatten(states):
        if name == "version":
            lines.append(f"    pub const VERSION: i64 = {value};")
            continue
        if not isinstance(value, int):
            raise TypeError(f"state code is not an integer: {name}")
        const_name = identifier(name)
        lines.append(f"    pub const {const_name}: i64 = {value};")
        state_entries.append((name, value))
    lines.extend(["", "    pub const ALL: &[(&str, i64)] = &["])
    for name, value in state_entries:
        lines.append(f"        ({json.dumps(name)}, {value}),")
    lines.extend(["    ];", "}", ""])
    return "\n".join(lines)


def render_kotlin(protocol: dict[str, Any], states: dict[str, Any]) -> str:
    lines = [
        "// @generated by tools/generate_contracts.py; do not edit.",
        "package org.disastermesh.android.domain",
        "",
        "object ProtocolConstants {",
    ]
    for name, value in flatten(protocol):
        value_type, literal = kotlin_literal(value)
        lines.append(f"    const val {identifier(name)}: {value_type} = {literal}")
    lines.extend(["}", "", "object PersistedStateCodes {"])
    for name, value in flatten(states):
        value_type, literal = kotlin_literal(value)
        lines.append(f"    const val {identifier(name)}: {value_type} = {literal}")
    lines.extend(["}", ""])
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"generated contract drift: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    protocol = tomllib.loads(PROTOCOL.read_text(encoding="utf-8"))
    states = tomllib.loads(STATES.read_text(encoding="utf-8"))
    results = [
        write_or_check(RUST_OUTPUT, render_rust(protocol, states), args.check),
        write_or_check(KOTLIN_OUTPUT, render_kotlin(protocol, states), args.check),
    ]
    if all(results):
        print("Contract constants are current")
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
